#!/usr/bin/env bash
#
# This is the script that builds the project documentation into ../doc.
#
# Generally you don't call this directly; instead you run `make doc`.

set -e

bundle install >/dev/null
bundle exec jekyll build
rm -rf ../docs/*
cp -R _site/* ../docs
