title: MailSpoon Documentation
email: andrew.net
description: Documentation for MailSpoon

baseurl: ""
url: ""

github_username: janklab
github:
  repository_nwo: janklab/MailSpoon
forkme_nwo: janklab/MailSpoon
footer-links:
  github: janklab/MailSpoon

permalink: pretty

exclude:
  - Gemfile*
  - README.md
  - make_doc

markdown: kramdown
theme: jekyll-theme-cayman
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    default_lang: matlab
asciidoc: {}
asciidoctor:
   base_dir: :docdir
   safe: unsafe
   attributes:
     stem: 
     imagesdir: /images
     source-highlighter: pygments
     pygments-stylesheet: css/asciidoc-pygments.css

keep_files:
- images
plugins:
  - asciidoctor-diagram
  - jekyll-asciidoc
  - jekyll-last-modified-at
  - jekyll-toc          # https://github.com/toshimaru/jekyll-toc
  - jekyll-sitemap      # https://github.com/jekyll/jekyll-sitemap
  # Not sure about this one:
  # - jekyll-paginate
